version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./backand:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "python manage.py  && python manage.py runserver 0.0.0.0:8000"
      

  db:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "5555:3306"
    env_file:
      - .env
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backand/static:/usr/share/nginx/doc

  celery:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "celery  -A configs worker -l info"

  redis:
    image: redis:alpine
    restart: on-failure

  flower:
    image: mher/flower:0.9.7
    restart: on-failure
    ports:
      - "1111:5555"
    command: [ "flower", "--broker=redis://redis:6379", "--port=5555" ]