version: "3.9"

services:
  app:
    build:
      context: .
    volumes:

    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "python manage.py  && python manage.py runserver 0.0.0.0:8000"
      

  db:
    image: mysql:8
    volumes:
    ports:
      - "5555:3306"
    env_file:
      - .env
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:

